name: EC2 Provisioning with Terraform + React App Deployment with Ansible

on:
  push:
    branches:
      - main    
    paths:
      - 'terraform/**'
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./terraform/
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init and Apply
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: get_ip
        working-directory: terraform
        run: |
          echo "Fetching public IP from Terraform output..."
          PUBLIC_IP=$(terraform output -raw instance_public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo $PUBLIC_IP

      - name: Set up Python and Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install ansible

      - name: Create ansible folder
        run: mkdir -p ansible

      - name: Copy SSH Private Key from GitHub Secret
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ansible/aws-key.pem
          chmod 400 ansible/aws-key.pem

      - name: Create Ansible Inventory File
        run: |
          echo "[react_app]" > ansible/inventory.ini
          echo "${{ env.PUBLIC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=ansible/aws-key.pem ansible_python_interpreter=/usr/bin/python3" >> ansible/inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/react_deploy.yml
